services:
  # prefilter_api:
  #   image: mlkod/lua-engine:prefilter_api
  #   # image: ${DOCKER_REGISTRY-}luaengineprefilter
  #   build:
  #     context: .
  #     dockerfile: LuaEngine.Prefilter/Dockerfile
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   container_name: prefilter_api
  #   depends_on:
  #     - scripts_api
  #     - rabbitmq
  #   volumes:
  #     - ../LuaEngine.Scripts/LuaEngine.Scripts.Models/bin/Debug:/root/.nuget/packages
  scripts_api:
    image: mlkod/lua-engine:scripts_api
    # image: ${DOCKER_REGISTRY-}luaenginescripts
    build:
      context: ../LuaEngine.Scripts
      dockerfile: LuaEngine.Scripts/Dockerfile
    ports:
      - "8082:8082"
      - "8083:8083"
    container_name: scripts_api
    depends_on:
      - scripts_db
    volumes:
      - ../LuaEngine.Scripts/LuaEngine.Scripts.Models/bin/Debug:/root/.nuget/packages
  scripts_db:
    image: mlkod/lua-engine:scripts_db
    # image: postgres:latest
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scripts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg1248
    volumes: 
      - db_data:/var/lib/postgresql/data
    container_name: scripts_db
  rabbitmq:
    image: mlkod/lua-engine:rabbitmq
    # image: rabbitmq:3.10.7-management
    build:
      context: ../rabbitmq
      dockerfile: Dockerfile
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    container_name: rabbitmq
volumes:
  db_data:
  rabbitmq_data:
