services:
  prefilter_api:
    image: mlkod/lua-engine:prefilter_api
    build:
      context: .
      dockerfile: LuaEngine.Prefilter/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: prefilter_api
    depends_on:
      - scripts_api
      - orchestrator_api
  orchestrator_api:
    image: mlkod/lua-engine:orchestrator_api
    build:
      context: ../LuaEngine.LuaOrchestrator
      dockerfile: LuaEngine.LuaOrchestrator/Dockerfile
    ports:
      - "8084:8084"
      - "8085:8085"
    container_name: orchestrator_api
    depends_on:
      - rabbitmq
  agent_api:
    image: mlkod/lua-engine:agent_api
    build:
      context: ../LuaEngine.LuaAgent
      dockerfile: LuaEngine.LuaAgent/Dockerfile
    ports:
      - "8086:8086"
      # - "8087:8087"
    container_name: agent_api
    depends_on:
      - orchestrator_api
  scripts_api:
    image: mlkod/lua-engine:scripts_api
    build:
      context: ../LuaEngine.Scripts
      dockerfile: LuaEngine.Scripts/Dockerfile
    ports:
      - "8082:8082"
      - "8083:8083"
    container_name: scripts_api
    depends_on:
      - scripts_db
    volumes:
      - ../LuaEngine.Scripts/LuaEngine.Scripts.Models/bin/Debug:/root/.nuget/packages
  scripts_db:
    image: mlkod/lua-engine:scripts_db
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=scripts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg1248
    volumes: 
      - db_data:/var/lib/postgresql/data
    container_name: scripts_db
  rabbitmq:
    image: mlkod/lua-engine:rabbitmq
    build:
      context: ../rabbitmq
      dockerfile: Dockerfile
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    container_name: rabbitmq
volumes:
  db_data:
  rabbitmq_data:
