name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '9.0.3'

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker images
        run: |
          docker compose -f LuaEngine.Prefilter/docker-compose.yml build
          
      - name: Test
        run: |
          dotnet test LuaEngine.Scripts/LuaEngine.Scripts.Tests/LuaEngine.Scripts.Tests.csproj --verbosity normal

      - name: Push Docker images
        run: |
          docker compose -f LuaEngine.Prefilter/docker-compose.yml push

      - name: Run services
        run: |
          docker compose -f LuaEngine.Prefilter/docker-compose.yml up -d

      - name: Shut down services
        run: |
          docker compose -f LuaEngine.Prefilter/docker-compose.yml down
